### ISSUE TITLE
Please source the correct autojump file in your shell's

### ISSUE THREAD

**Issue by GopherJ** [xen0n/autojump-rs#23]
➜  ~ autojump cfg
Please source the correct autojump file in your shell's
startup file. For more information, please reinstall autojump
and read the post installation instructions.

**Comment by nyaascii** [comment]
*I am not a maintainer or a contributor, just a user so I might be wrong*

Hii!

I suspect the problem is that you don't have the original `autojump`'s shell scripts *sourced*.
I had the same issue and resolved it by copying those scripts and adding them to my init file:

![uwu](https://user-images.githubusercontent.com/17256443/85205944-e0323900-b31e-11ea-8e5b-ea7b73876281.png)

I hope it works!
Thank you 🙇‍♀️

**Comment by xen0n** [comment]
Hi @GopherJ, this package in its current form is incomplete (*strictly* meant to be used as a drop-in), so @nyaascii is correct.

As the autojump upstream seems dead since 2018, I'm planning to incorporate all its remaining parts (including the shell integrations of course) and cut a new release Soon :tm:. After the package enters your distro you can simply replace `autojump` with this one.

**Comment by GopherJ** [comment]
@xen0n Really looking forward to seeing it. I'm on Linux mint 20beta currectly.

BTW, I just tried to source https://github.com/wting/autojump/blob/master/bin/autojump.zsh as @nyaascii suggested.

However, after that I still cannot use autojump, I mean when I execute `autojump foo`, it just returns `.`

Am I doing wrong?

**Comment by xen0n** [comment]
@GopherJ You can run `autojump -s` to see if your desired directory is in the database. By design `autojump` can only jump to directories you've already `cd`-ed to at least once, or it would have to scan the entirety of your disk, wouldn't it :joy:

**Comment by GopherJ** [comment]
@xen0n Cool thanks It worked, sorry I haven't used `autojump` tool before.

**Comment by nyaascii** [comment]
I would suggest using `cd` with an interactive filter like [skim](https://github.com/lotabout/skim] (fzf's replacement written in Rust) 😊 

With an abbreviation in Fish `csk` -> `cd (sk)`, it's easier to fill the database (and navigate to new, unindexed directories).
Plus it's fun to use it, at least for me (๑˃̵ᴗ˂̵)و

Thank you for reading this and stay safe 🙇‍♀️
